version: '3.4'

services:
  ingress:
    image: ${DOCKER_REGISTRY-}akkaoncore.ingress
    build:
      context: ./Ingress/
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 44300:443

  akkaoncore.web:
    image: ${DOCKER_REGISTRY-}akkaoncore.web
    build:
      context: .
      dockerfile: AkkaOnCore.WebAPI/Dockerfile

  eventstore-node:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - "~/events:/var/lib/eventstore"

  akkaoncore.query:
    image: ${DOCKER_REGISTRY-}akkaoncore.query
    build:
      context: .
      dockerfile: AkkaOnCore.QueryAPI/Dockerfile

  akkaoncore.readhub:
    image: ${DOCKER_REGISTRY-}akkaoncore.readhub
    build:
      context: .
      dockerfile: AkkaOnCore.ReadHub/Dockerfile
    ports:
      - "44333:443"

  akkaoncore.command:
    image: ${DOCKER_REGISTRY-}akkaoncore.command
    build:
      context: .
      dockerfile: AkkaOnCore.CommandAPI/Dockerfile
