version: '3.4'

services:
  akkaoncore:
    image: ${DOCKER_REGISTRY-}akkaoncore
    build:
      context: .
      dockerfile: AkkaOnCore/Dockerfile
    ports:
      - "44331:443"

  eventstore-node:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - "~/events:/var/lib/eventstore"

  akkaoncore.query:
    image: ${DOCKER_REGISTRY-}akkaoncore.query
    build:
      context: .
      dockerfile: AkkaOnCore.QueryAPI/Dockerfile
    ports:
      - "44332:443"

  akkaoncore.readhub:
    image: ${DOCKER_REGISTRY-}akkaoncore.readhub
    build:
      context: .
      dockerfile: AkkaOnCore.ReadHub/Dockerfile
    ports:
      - "44333:443"