@webhost = http://localhost:44300
@queryhost = http://localhost:44300/api
@commandhost = http://localhost:44300/api
@signalrhost = https://localhost:44333
@meetingid = a8ca076b-630f-48d3-b265-460c0478a402

### Home
GET {{webhost}}

### Start Meeting Command
POST {{commandhost}}/meetings
Content-Type: application/json

{
    "name": "Flump"
}

### Add Agenda Item Command
POST {{commandhost}}/meeting/{{meetingid}}/addtoagenda
Content-Type: application/json

{
    "description": "Something"
}

### Query Meetings List
GET {{queryhost}}/meetings

### Test SignalR
GET {{signalrhost}}