@webhost = http://localhost:44300
@queryhost = http://localhost:44300/api
@commandhost = http://localhost:44300/api
@signalrhost = https://localhost:44333

### Home
GET {{webhost}}

### Start Meeting Command
POST {{commandhost}}/meetings
Content-Type: application/json

{
    "name": "D Meeting"
}

### Query Meetings List
GET {{queryhost}}/meetings

### Test SignalR
GET {{signalrhost}}