@host = https://localhost:44331
@queryhost = https://localhost:44332

### Home
GET {{host}}

### Start Meeting
POST {{host}}/api/meetings
Content-Type: application/json

{
    "name": "Another Meeting"
}

### Query Meetings List
GET {{queryhost}}/api/meetings